version: '3.8'
services:

  odoo:
    image: odoo:16.0
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
  
  postgres:
    image: postgres:15.3
    env_file: .env
    volumes:
      - odoo-postgres:/var/lib/postgresql/data/pgdata

volumes:
  odoo-data:
  odoo-postgres:
